homebrew_project/homebrew/brews/urls.py
from django.conf.urls import patterns, url

from brews.forms import GravityReadingForm, TemperatureReadingForm
from brews.models import GravityReading, TemperatureReading
from brews.views.brew import BrewCreateView, BrewDetailView, ReadingCreateView, ReadingUpdateView, ReadingDeleteView, \
    CustomiseRecipeRedirectView, BrewListView, BrewUpdateView, BrewDeleteView, BrewNoteCreateView, BrewNoteUpdateView, \
    BrewNoteDeleteView, recipes_for_style, BrewMonthArchiveView, BrewYearArchiveView, BrewArchiveRedirectView

__author__ = 'sam'

urlpatterns = patterns(
    '',
    url(r'^create$', BrewCreateView.as_view(), name='brew-create'),
    url(r'^create/recipes_for_style/$', recipes_for_style, name='recipes-for-style'),
    url(r'^view/(?P<slug>[\w-]+)/$', BrewDetailView.as_view(template_name='brew/brew_detail.html'),
        name='brew-detail'),


    url(r'^view/(?P<slug>[\w-]+)/gravity_readings/add/$',
        ReadingCreateView.as_view(model=GravityReading, form_class=GravityReadingForm),
        name='brew-detail-gravity-add'),
    url(r'^view/(?P<slug>[\w-]+)/temperature_readings/add/$',
        ReadingCreateView.as_view(model=TemperatureReading, form_class=TemperatureReadingForm),
        name='brew-detail-temp-add'),
    url(r'^view/(?P<slug>[\w-]+)/gravity_readings/update/(?P<pk>\d+)/$',
        ReadingUpdateView.as_view(model=GravityReading, form_class=GravityReadingForm),
        name='brew-detail-gravity-update'),
    url(r'^view/(?P<slug>[\w-]+)/temperature_readings/update/(?P<pk>\d+)/$',
        ReadingUpdateView.as_view(model=TemperatureReading, form_class=TemperatureReadingForm),
        name='brew-detail-temp-update'),
    url(r'^view/(?P<slug>[\w-]+)/gravity_readings/delete/(?P<pk>\d+)/$',
        ReadingDeleteView.as_view(model=GravityReading),
        name='brew-detail-gravity-delete'),
    url(r'^view/(?P<slug>[\w-]+)/temperature_readings/delete/(?P<pk>\d+)/$',
        ReadingDeleteView.as_view(model=TemperatureReading),
        name='brew-detail-temp-delete'),


    url(r'^view/(?P<slug>[\w-]+)/customise_recipe/', CustomiseRecipeRedirectView.as_view(), name='brew-customise'),
    url(r'^list/$', BrewListView.as_view(), name='brew-list'),
    url(r'^update/(?P<slug>[\w-]+)/$', BrewUpdateView.as_view(), name='brew-update'),
    url(r'^delete/(?P<slug>[\w-]+)/$', BrewDeleteView.as_view(), name='brew-delete'),
    url(r'^view/(?P<slug>[\w-]+)/notes/create/(?P<note_type>\d+)/$', BrewNoteCreateView.as_view(), name='brew-note-create'),
    url(r'^view/(?P<slug>[\w-]+)/notes/edit/(?P<pk>\d+)/$', BrewNoteUpdateView.as_view(), name='brew-note-edit'),
    url(r'^view/(?P<slug>[\w-]+)/notes/delete/(?P<pk>\d+)/$', BrewNoteDeleteView.as_view(), name='brew-note-delete'),

    url(r'^archive/$', BrewArchiveRedirectView.as_view(),
        name='brew-archive'),
    url(r'^archive/(?P<year>\d{4})/$', BrewYearArchiveView.as_view(),
        name='brew-archive-year'),
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d+)/$', BrewMonthArchiveView.as_view(month_format='%m'),
        name='brew-archive-month'),
)

homebrew_project/homebrew/brews/models.py
import datetime

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Max
from uuslug import uuslug
from recipes import calculations

from recipes.models import BaseRecipe, AllGrainRecipe, ExtractRecipe


class BrewManager(models.Manager):
    def for_user(self, user):
        return self.get_queryset().filter(owner=user)

    def latest_brews(self, user):
        return self.for_user(user).select_related('recipe').order_by('-brew_date')[:5]


class Brew(models.Model):
    objects = BrewManager()

    recipe = models.ForeignKey(BaseRecipe)
    brew_date = models.DateField()
    bottle_date = models.DateField(blank=True, null=True)
    # gravityreading_set
    # temperaturereading_set
    recipe_editable = models.BooleanField(default=False, editable=False)  # Has the recipe been cloned yet?
    owner = models.ForeignKey(User)

    slug = models.SlugField(editable=False)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.id:
            self.slug = uuslug(self.recipe.name, instance=self, max_length=50)
        super().save(force_insert, force_update, using, update_fields)

    def clone_recipe_for_update(self):
        # Get a new reference to the recipe
        recipe = BaseRecipe.objects.get(pk=self.recipe.pk)

        if hasattr(recipe, 'extractrecipe'):
            recipe = recipe.extractrecipe
            if hasattr(recipe, 'allgrainrecipe'):
                recipe = recipe.allgrainrecipe

        recipe.clone_for_batch(self.owner)

        self.recipe = recipe
        self.recipe_editable = True

        self.save()

    def get_absolute_url(self):
        return reverse('brew-detail', kwargs={'slug': self.slug})

    def get_estimated_ready_date(self):
        estimated_date = None
        if self.bottle_date:
            kwargs = {}
            if self.recipe.conditioning_time_quantifier == 'd':
                kwargs = {'days': self.recipe.conditioning_time}
            elif self.recipe.conditioning_time_quantifier == 'w':
                kwargs = {'weeks': self.recipe.conditioning_time}
            elif self.recipe.conditioning_time_quantifier == 'y':
                kwargs = {'days': self.recipe.conditioning_time * 365}

            # Don't calculate a date if the conditioning time quantifier is invalid
            if len(kwargs.keys()) == 1:
                estimated_date = self.bottle_date + datetime.timedelta(**kwargs)

        return estimated_date

    def alcohol_by_volume(self):
        if self.gravityreading_set.count() > 0:
            qs = self.gravityreading_set.order_by('time')

            original_gravity = qs.first()
            final_gravity = qs.last()

            return calculations.alcohol_by_volume(original_gravity.value, final_gravity.value)
        else:
            return 0

    def priming_sucrose(self):
        # Get the highest temperature
        max_temp = self.temperaturereading_set.aggregate(Max('value'))['value__max']
        return calculations.priming_sucrose(self.recipe.target_volume, max_temp, self.recipe.style.co_volume)

    def priming_dextrose(self):
        # Get the highest temperature
        max_temp = self.temperaturereading_set.aggregate(Max('value'))['value__max']
        return calculations.priming_dextrose(self.recipe.target_volume, max_temp, self.recipe.style.co_volume)

    def priming_dme(self):
        # Get the highest temperature
        max_temp = self.temperaturereading_set.aggregate(Max('value'))['value__max']
        return calculations.priming_dme(self.recipe.target_volume, max_temp, self.recipe.style.co_volume)


class Reading(models.Model):
    """
    Abstract base class for any kind of reading, e.g. Gravity Reading, Temperature Reading
    """
    batch = models.ForeignKey(Brew)
    time = models.DateTimeField()
    value = models.DecimalField(max_digits=19, decimal_places=10)

    class Meta:
        abstract = True

    def get_absolute_url(self):
        return reverse('brew-detail', kwargs={'slug': self.batch.slug})


class GravityReading(Reading):

    class Meta:
        ordering = ('time', )

    def __str__(self):
        return 'SG {value} @ {time}'.format(value=self.value, time=self.time)

    def get_absolute_url(self):
        return super().get_absolute_url()+'#tab_gravity_readings'

    def get_update_url(self):
        return reverse('brew-detail-gravity-update', kwargs={'slug': self.batch.slug, 'pk': self.pk})

    def get_delete_url(self):
        return reverse('brew-detail-gravity-delete', kwargs={'slug': self.batch.slug, 'pk': self.pk})

    def get_formatted_value(self):
        return self.value


class TemperatureReading(Reading):

    class Meta:
        ordering = ('time', )

    def __str__(self):
        return '{value:0.2f}°C @ {time}'.format(value=self.value, time=self.time)

    def get_absolute_url(self):
        return super().get_absolute_url()+'#tab_temp_readings'

    def get_update_url(self):
        return reverse('brew-detail-temp-update', kwargs={'slug': self.batch.slug, 'pk': self.pk})

    def get_delete_url(self):
        return reverse('brew-detail-temp-delete', kwargs={'slug': self.batch.slug, 'pk': self.pk})

    def get_formatted_value(self):
        return '{:0.2f}°C'.format(self.value)


class BrewNoteManager(models.Manager):
    def appearance_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.APPEARANCE)

    def aroma_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.AROMA)

    def boil_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.BOIL)

    def feel_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.FEEL)

    def fermentation_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.FERMENTATION)

    def flavour_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.FLAVOUR)

    def general_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.GENERAL)

    def mash_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.MASH)

    def overall_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.OVERALL)

    def didnt_work_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.DIDNT_WORK)

    def what_worked_set(self, brew):
        return self.for_type(brew=brew, note_type=BrewNote.WHAT_WORKED)

    def for_type(self, brew, note_type):
        return self.get_queryset().filter(brew=brew, type=note_type).order_by('pk')


class BrewNote(models.Model):
    GENERAL = 1
    MASH = 2
    BOIL = 3
    FERMENTATION = 4
    APPEARANCE = 5
    AROMA = 6
    FLAVOUR = 7
    FEEL = 8
    OVERALL = 9
    DIDNT_WORK = 10
    WHAT_WORKED = 11

    NOTE_TYPES = (
        (APPEARANCE, 'Appearance'),
        (AROMA, 'Aroma'),
        (BOIL, 'Boil'),
        (FEEL, 'Feel'),
        (FERMENTATION, 'Fermentation'),
        (FLAVOUR, 'Flavour'),
        (GENERAL, 'General'),
        (MASH, 'Mash'),
        (OVERALL, 'Overall'),
        (DIDNT_WORK, 'What Didn\'t Work'),
        (WHAT_WORKED, 'What Worked'),
    )

    objects = BrewNoteManager()

    brew = models.ForeignKey(Brew)
    type = models.IntegerField(choices=NOTE_TYPES)
    note = models.TextField()
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.note

    def get_absolute_url(self):
        return reverse('brew-detail', kwargs={'slug': self.brew.slug})+'#tab_notes'

    def get_update_url(self):
        return reverse('brew-note-edit', kwargs={'slug': self.brew.slug, 'pk': self.pk})

    def get_delete_url(self):
        return reverse('brew-note-delete', kwargs={'slug': self.brew.slug, 'pk': self.pk})

homebrew_project/homebrew/recipes/views/ingredient.py
from django.core.urlresolvers import reverse
from django.views.generic import UpdateView, DeleteView, CreateView, DetailView
from permissionsx.contrib.django.views import DjangoViewMixin

from homebrew.permissions import UserIsAuthenticatedPermissions
from recipes.permissions import ObjectOwnerPermissions
from recipes.views.generic import PagedFilteredTableView, get_dependant_objects, RememberPageParametersMixin, \
    FormViewMessageMixin


__author__ = 'sam'


class IngredientCreateView(FormViewMessageMixin, DjangoViewMixin, CreateView):
    template_name = 'ingredient/ingredient_create.html'

    # Authorisation
    permissions = UserIsAuthenticatedPermissions()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.model.__name__
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user
        return initial


class IngredientListView(RememberPageParametersMixin, PagedFilteredTableView):
    template_name = 'ingredient/ingredient_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.model.__name__
        context['create_url'] = reverse(str(self.model.__name__ + '-create').lower())
        return context

    def get(self, request, *args, **kwargs):
        self.queryset = self.model.objects.public_or_owner(request.user)
        return super().get(request, *args, **kwargs)


class IngredientUpdateView(FormViewMessageMixin, DjangoViewMixin, UpdateView):
    template_name = 'ingredient/ingredient_update.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Authorisation
        self.permissions = ObjectOwnerPermissions(model_class=self.model)


class IngredientDeleteView(FormViewMessageMixin, DjangoViewMixin, DeleteView):
    template_name = 'ingredient/ingredient_delete.html'
    success_view_name = ''
    success_message = '{} successfully deleted'
    failure_message = 'Error while deleting {}'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Authorisation
        self.permissions = ObjectOwnerPermissions(model_class=self.model)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        dependants = get_dependant_objects(self.get_object())
        dependant_recipes = set([x.recipe for x in dependants])
        context['protected'] = dependant_recipes

        return context

    def get_success_url(self):
        return reverse(self.success_view_name)


class IngredientDetailView(DetailView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Also calculate how big the tag should be displayed, up to a max of 28px
        similar_objects = [(x, min(x.similar_tags * 2 + 12, 28)) for x in self.object.tags.similar_objects()]
        context['similar_objects'] = similar_objects

        return context

homebrew_project/homebrew/templates/ingredient/fermentable_detail.html
{% extends "base.html" %}
{% load permissionsx_tags %}
{% load humanize %}

{% block page_title %}{{ object.name }}<div class="pull-right">
        <span class="label label-primary" style="background-color: {{ object.html_colour }}">{{ object.get_type_display }}</span>
    </div>{% endblock page_title %}
{% block head_title %}{{ object.name }}{% endblock head_title %}
{% block content %}
    {% permissions 'recipes.permissions.FermentableOwnerPermissions' slug=fermentable.slug as user_owns_fermentable %}

    <div class="panel panel-default">
        <div class="panel-body">
            <p>
                {{ object.description }}
            </p>
            <div class="row">
                <div class="col-md-2"><label class="control-label">Lovibond Rating</label></div>
                <div class="col-md-1">{{ object.lovibond_rating|floatformat:2 }}</div>
                <div class="col-md-3"><label class="control-label">Standard Reference Method (SRM)</label></div>
                <div class="col-md-1">{{ object.get_srm|floatformat:2  }}</div>
                <div class="col-md-3"><label class="control-label">European Brewery Convention (EBC)</label></div>
                <div class="col-md-1">{{ object.get_ebc|floatformat:2  }}</div>
            </div>
            <div class="row">
                <div class="col-md-2"><label class="control-label">Extract Potential</label></div>
                <div class="col-md-1">{{ object.extract_potential }}%</div>
            </div>
            <div class="row">
                <div class="col-md-2"><label class="control-label">Requires Mashing?</label></div>
                <div class="col-md-1">{{ object.requires_mashing|boolean }}</div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Tags</div>
        <div class="panel-body">
            {% for t in object.tags.names %}
                {% if not forloop.last %}
                    {{ t }},
                {% else %}
                    {{ t }}
                {% endif %}
            {% endfor %}
        </div>
        <div class="panel-heading">Similar</div>
        <div class="panel-body">
            {% for t, font_height in similar_objects %}
                <span style="margin: 0px 15px; font-size: {{ font_height }}px"><a href="{{ t.get_absolute_url }}">{{ t }}</a></span>
            {% endfor %}
        </div>
    </div>

    <div class="btn-group">
        <a href="{% url "fermentable-list" %}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span>Back</a>
        {% if user_owns_fermentable %}
            <a href="{% url "fermentable-update" object.slug %}" class="btn btn-primary">Update</a>
            <a href="{% url "fermentable-delete" object.slug %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>Delete</a>
        {% endif %}
    </div>
{% endblock %}

homebrew_project/homebrew/templates/ingredient/hop_detail.html
{% extends "base.html" %}
{% load permissionsx_tags %}


{% block page_title %}{{ object.name }}{% endblock page_title %}
{% block head_title %}{{ object.name }}{% endblock head_title %}
{% block content %}
    {% permissions 'recipes.permissions.HopOwnerPermissions' slug=object.slug as user_owns_hop %}
    <div class="panel panel-default">
        <div class="panel-body">
            <p>
                {{ object.description }}
            </p>
            <div class="row">
                <div class="col-md-2"><label class="control-label">Country Of Origin</label></div>
                <div class="col-md-2">{{ object.country_of_origin }}</div>
            </div>
            <div class="row">
                <div class="col-md-2"><label class="control-label">Alpha Acid Range</label></div>
                <div class="col-md-2">{{ object.alpha_acid_low }}% - {{ object.alpha_acid_high }}%</div>
            </div>
            <div class="row">
                <div class="col-md-2"><label class="control-label">Intensity</label></div>
                <div class="col-md-2">{{ object.intensity }} / 10</div>
            </div>

        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Tags</div>
        <div class="panel-body">
            {% for t in object.tags.names %}
                {% if not forloop.last %}
                    {{ t }},
                {% else %}
                    {{ t }}
                {% endif %}
            {% endfor %}
        </div>
        <div class="panel-heading">Similar</div>
        <div class="panel-body">
            {% for t, font_height in similar_objects %}
                <span style="margin: 0px 15px; font-size: {{ font_height }}px"><a href="{{ t.get_absolute_url }}">{{ t }}</a></span>
            {% endfor %}
        </div>
    </div>


    <div class="btn-group">
        <a href="{% url "hop-list" %}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span>Back</a>
        {% if user_owns_hop %}
            <a href="{% url "hop-update" object.slug %}" class="btn btn-primary">Update</a>
            <a href="{% url "hop-delete" object.slug %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>Delete</a>
        {% endif %}
    </div>
{% endblock %}

homebrew_project/homebrew/templates/ingredient/ingredient_create.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-duallistbox.css" %}">
{% endblock extra_css %}

{% block extra_js %}
    <script src="{% static "js/jquery.bootstrap-duallistbox.js" %}"></script>
    <script>
        $(function(){
            $('.select-multiple').bootstrapDualListbox({
                'moveOnSelect': false
            });
        });
    </script>
{% endblock extra_js %}
{% block page_title %}Create {{ title }}{% endblock page_title %}
{% block head_title %}Create {{ title }}{% endblock head_title %}
{% block content %}
    <form method="post" action="{{ request.path }}">
        {% csrf_token %}
        {% for field in form %}
            {% bootstrap_field field %}
        {% endfor %}
        <div class="btn-group">
            <a href="{% url form.list_viewname %}" class="btn btn-default">Cancel</a>
            <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit">
        </div>
    </form>
{% endblock %}

homebrew_project/homebrew/templates/ingredient/ingredient_delete.html
{% extends "base.html" %}
{% block page_title %}Delete {{ object }}{% endblock page_title %}
{% block head_title %}Delete {{ object }}{% endblock head_title %}
{% block content %}

    {% if protected %}
        <p>{{ object }} cannot be deleted because it is used in some recipes:</p>
        <ul>
        {% for o in protected %}
            {% if o.public or o.owner == user %}
                <li><a href="{{ o.get_absolute_url }}">{{ o.name }}</a></li>
            {% else %}
                <li>Private recipe</li>
            {% endif %}
        {% endfor %}
        </ul>
        <a href="{{ object.get_absolute_url }}" class="btn btn-default">Back</a>
    {% else %}
        <p>Are you sure you wish to delete {{ object }}?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" name="Yes" class="btn btn-danger">Yes</button>
            <a href="{{ object.get_absolute_url }}" class="btn btn-success">No</a>
        </form>
    {% endif %}
{% endblock %}

homebrew_project/homebrew/templates/ingredient/ingredient_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}
{% load sniplates %}
{% block page_title %}{{ title }}{% endblock page_title %}
{% block head_title %}{{ title }}{% endblock head_title %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Search</h3>
        </div>
        <div class="panel-body">
            {% widget "bootstrap:search_form" %}
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title" style="display: inline">{{ title }}</h3>
            {% if user_is_authenticated %}
                <div class="pull-right">
                <a href="{{ create_url }}" class="btn btn-primary">Create</a>
                    </div>
                <div class="clearfix"></div>
            {% endif %}
        </div>
        <div class="panel-body">
            {% render_table table %}
        </div>
    </div>



{% endblock %}

homebrew_project/homebrew/templates/ingredient/ingredient_update.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-duallistbox.css" %}">
{% endblock extra_css %}

{% block extra_js %}
    <script src="{% static "js/jquery.bootstrap-duallistbox.js" %}"></script>
    <script>
        $(function(){
            $('.select-multiple').bootstrapDualListbox({
                'moveOnSelect': false
            });
        });
    </script>
{% endblock extra_js %}
{% block page_title %}Update {{ object.name }}{% endblock page_title %}
{% block head_title %}Update {{ object.name }}{% endblock head_title %}
{% block content %}
    <form method="post" action="{{ request.path }}">
        {% csrf_token %}
        {% for field in form %}
            {% bootstrap_field field %}
        {% endfor %}
        <div class="btn-group">
            <a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
            <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit">
        </div>
    </form>
{% endblock %}

homebrew_project/homebrew/templates/ingredient/other_detail.html
{% extends "base.html" %}
{% load permissionsx_tags %}

{% block page_title %}{{ object.name }}{% endblock page_title %}
{% block head_title %}{{ object.name }}{% endblock head_title %}
{% block content %}
    {% permissions 'recipes.permissions.OtherOwnerPermissions' slug=other.slug as user_owns_other %}

    <div class="panel panel-default">
        <div class="panel-body">
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Tags</div>
        <div class="panel-body">
            {% for t in object.tags.names %}
                {% if not forloop.last %}
                    {{ t }},
                {% else %}
                    {{ t }}
                {% endif %}
            {% endfor %}
        </div>
        <div class="panel-heading">Similar</div>
        <div class="panel-body">
            {% for t, font_height in similar_objects %}
                <span style="margin: 0px 15px; font-size: {{ font_height }}px"><a href="{{ t.get_absolute_url }}">{{ t }}</a></span>
            {% endfor %}
        </div>
    </div>

    <div class="btn-group">
        <a href="{% url "other-list" %}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span>Back</a>
        {% if user_owns_other %}
            <a href="{% url "other-update" object.slug %}" class="btn btn-primary">Update</a>
            <a href="{% url "other-delete" object.slug %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>Delete</a>
        {% endif %}
    </div>
{% endblock %}

homebrew_project/homebrew/templates/ingredient/yeast_detail.html
{% extends "base.html" %}
{% load permissionsx_tags %}

{% block page_title %}{{ object }}{% endblock page_title %}
{% block head_title %}{{ object.name }}{% endblock head_title %}
{% block content %}
    {% permissions 'recipes.permissions.YeastOwnerPermissions' slug=yeast.slug as user_owns_yeast %}

    <div class="panel panel-default">
        <div class="panel-body">
            <p>
                {{ object.description }}
            </p>
            <label class="control-label">Style(s)</label>
            <ul>
                {% for s in object.style.all %}
                <li>{{ s }}</li>
                {% endfor %}
            </ul>
            <label class="control-label">Alternative(s)</label>
            <ul>
                {% for a in object.alternatives.all %}
                <li><a href="{% url "yeast-detail" a.slug %}">{{ a }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Tags</div>
        <div class="panel-body">
            {% for t in object.tags.names %}
                {% if not forloop.last %}
                    {{ t }},
                {% else %}
                    {{ t }}
                {% endif %}
            {% endfor %}
        </div>
        <div class="panel-heading">Similar</div>
        <div class="panel-body">
            {% for t, font_height in similar_objects %}
                <span style="margin: 0px 15px; font-size: {{ font_height }}px"><a href="{{ t.get_absolute_url }}">{{ t }}</a></span>
            {% endfor %}
        </div>
    </div>

    <div class="btn-group">
        <a href="{% url "yeast-list" %}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span>Back</a>
        {% if user_owns_yeast %}
            <a href="{% url "yeast-update" object.slug %}" class="btn btn-primary">Update</a>
            <a href="{% url "yeast-delete" object.slug %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>Delete</a>
        {% endif %}
    </div>
{% endblock %}